### ISSUE TITLE
Crashing on Minecraft 1.19.4

### ISSUE THREAD

**Issue by OriginCode** [VazkiiMods/Neat#129]
Log: https://gist.github.com/OriginCode/9a1cd3cba246af478cefb09dde4ba375

```
java.lang.NoSuchMethodError: 'int net.minecraft.class_327.method_27521(java.lang.String, float, float, int, boolean, org.joml.Matrix4f, net.minecraft.class_4597, boolean, int, int)'
	at vazkii.neat.HealthBarRenderer.hookRender(HealthBarRenderer.java:250)
	at net.minecraft.class_898.handler$cda000$neat$renderHealthBar(class_898.java:1535)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1572)
	at net.minecraft.class_761.method_22710(class_761.java:1322)
	at net.minecraft.class_757.method_3188(class_757.java:1100)
	at net.minecraft.class_757.method_3192(class_757.java:872)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:527)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```

**Comment by OriginCode** [comment]
Turns out I installed the wrong neat version, nvm.
